@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FindrParser" as FindrParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1 from/Candidates")
activate LogicManager

LogicManager -> FindrParser : parseCommand("delete 1 from/Candidates")
activate FindrParser

create DeleteCommandParser
FindrParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> FindrParser
deactivate DeleteCommandParser

FindrParser -> DeleteCommandParser : parse("1 from/Candidates")
activate DeleteCommandParser

DeleteCommandParser -> ParserUtil : parseIndex("1")
activate ParserUtil
ParserUtil --> DeleteCommandParser : Index
deactivate ParserUtil

DeleteCommandParser -> ParserUtil : parseStage("Candidates")
activate ParserUtil
ParserUtil --> DeleteCommandParser : Stage
deactivate ParserUtil

create DeleteCommand
DeleteCommandParser -> DeleteCommand : new DeleteCommand(Index, Stage)
activate DeleteCommand
DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> FindrParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> FindrParser
destroy DeleteCommandParser

FindrParser --> LogicManager : d
deactivate FindrParser

LogicManager -> DeleteCommand : execute(m)
activate DeleteCommand

DeleteCommand -> Model : deleteCandidate(person)
activate Model
Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult
CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : r
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
