@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedFindr" as VersionedFindr MODEL_COLOR
end box

[-> Model : undoFindr()
activate Model

Model -> VersionedFindr : undo()
activate VersionedFindr

VersionedFindr -> VersionedFindr :resetData(ReadOnlyFindr)
VersionedFindr --> Model :
deactivate VersionedFindr

[<-- Model
deactivate Model

@enduml
